### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by gboston** [datocms/react-datocms#8] opened 2020-05-05 14:48 UTC
Is there some degraded support for IE11? Seem to be some issues with intersection-observer and Fetch API?

**Comment by matjack1** [comment] 2020-05-06 06:27
we should support it @gboston we'll have a look as soon as possible!

**Comment by stefanoverna** [comment] 2020-05-07 07:30
@gboston  v1.2.2 should now work, could you please try it and report back? 😄 

Also, closing as duplicate of #6

**Closed by stefanoverna** 2020-05-07 07:30 UTC
