### ISSUE TITLE
Full screen images

### ISSUE THREAD

**Issue by jordykoppen** [datocms/react-datocms#12] opened 2020-05-18 18:59 UTC
Currently I'm trying to make a hero on my page that displays a full screen image. Traditionally, I can do this with setting a background url or giving an image height 100% and using object-cover to scale properly. Of course this approach would take away the lovely progressive loading which I'm here for 😁

I wonder if it is possible to get extra config on the Image component to achieve this behaviour. the picture and root node already get the posbility to add extra styling and or classnames and maybe this could be added to the `<img />` as well.

Or maybe, I'm completely clueless that there's already a way to achieve this 😅

**Comment by stefanoverna** [comment] 2020-05-19 04:05
Hi! Making this a duplicate of #5 :)

**Closed by stefanoverna** 2020-05-19 04:05 UTC
