### ISSUE TITLE
fadeInDuration is not working

### ISSUE THREAD

**Issue by BrunoQuaresma** [datocms/react-datocms#17] opened 2020-12-18 20:46 UTC
I tried to use fadeInDuration with a diff value but this is not working. You can try using `fadeInDuration={999999}` and you will see the duration is the same.

**Comment by matjack1** [comment] 2020-12-21 10:17
Thank you @BrunoQuaresma we are going to try reproducing and get back to you

**Comment by stefanoverna** [comment] 2021-01-04 08:55
Hey @BrunoQuaresma sorry for the delay, but seems to be working for me.. :/
Any ideas how we can reproduce it?

![2021-01-04 09 48 50](https://user-images.githubusercontent.com/51573/103517452-6d2f8080-4e72-11eb-99f9-cfd2c947c8c7.gif)

**Comment by stefanoverna** [comment] 2021-01-04 08:56
I'm gonna close this for now, but feel free to reopen if you have more info to share!

**Closed by stefanoverna** 2021-01-04 08:56 UTC
